<h4>
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
</h4>

In [18]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

A list is a built-in data type in Python that stores a collection of items, and it can store elements of different data types. It is implemented as a dynamic array, which means it can grow or shrink in size as needed.

An array is a data structure that stores a fixed-size sequential collection of elements of the same type. It is not a built-in data type in Python, but it can be created using libraries such as NumPy or array.

In [19]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


<h4>Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.</h4>

In [20]:
#  data type of elements of the list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
#  data type of elements of the array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


<h4>Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
</h4>
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [22]:
array_list = np.array(object = list_, dtype = int)
#  data type of elements of the list_
for i in list_:
    print(type(i))

#  data type of elements of the array_list
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

<h4>Q4. Write a code to find the following characteristics of variable, num_array:</h4><br>
(i) shape <br>
(ii) size

In [24]:
print(num_array.shape)

(2, 3)


In [25]:
print(num_array.size)

6


<h4>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
mat =  np.zeros((3,3))
print(mat)
print('Size of the matirix : ',mat.size)
print('Shape of the matirix : ',mat.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size of the matirix :  9
Shape of the matirix :  (3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
identity_matrix = np.identity(5, dtype="int")
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


<h4>OR</h4>

In [17]:
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
